### ISSUE TITLE
1.13

### ISSUE THREAD

**Issue by Finguimbrine** [Energy0124/MCFreedomLauncher#26]
Pls add 1.13 versions in the launcher
and your launcher is not full of bugs, the launcher is almost perfect, for me only missing 1.13
see my launcher: http://www.mediafire.com/file/g9wss7t4bf9qe4m/Finguim43+LauncherV2.zip

**Comment by LightWayUp** [comment]
The version you uploaded has been long deprecated. For security and other reasons ( such as incompatibility with newer versions of Minecraft ), I strongly advise against using it. I have uncommitted code stored locally, with updated dependencies, miscellaneous feature enhancements, and cleaned up proprietary Mojang code. Later alpha versions would also include an updater, internationalization support, and actual news feed tab instead of a JavaFX webview browser.

As for 1.13+ support, see #23.
